# Generated by Django 4.2.6 on 2023-12-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsmapp', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
