# Generated by Django 4.2.6 on 2023-12-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsmapp', '0005_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
