# Generated by Django 4.2.6 on 2023-12-18 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsmapp', '0006_rename_firstname_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vsmapp.customuser')),
            ],
        ),
    ]
